apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: default
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: node
        command: ["/bin/sh"]
        args: ["-c", "cd /app && npm start"]
        stdin: true
        ports:
          - containerPort: 3000
        volumeMounts:
        - mountPath: /app
          name: app-volume
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: pvc-nodejs              
