apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-mongodb
spec:
  selector:
    matchLabels:
      db: mongo
  serviceName: "statefulset-mongodb"    
  replicas: 2
  template:
    metadata:
      labels:
        db: mongo
    spec:
      containers:
        - name: statefulset-mongo
          image: mongo
          ports:
            - containerPort: 27017
         
          volumeMounts:
            - name: mongo-volume
              mountPath: /mnt/efs/fs1/mongodb
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      accessModes: 
        - ReadWriteMany
      resources:
        requests:
          storage: 5Mi