apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    name: pvc-mongodb  
  hostPath:
    path: /pv/mongodb
