apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nodejs
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    name: pvc-nodejs  
  hostPath:
    path: /mnt/efs/fs1/nodejs
